stmts = { stmt } ;

stmt = if_stmt
     | while_stmt
     | [ expr ] ";"
     ;

if_stmt = if_expr ;

while_stmt = "while" expr "{" stmts "}" ;

expr = "(" expr ")"
     | term { ("+" | "-") term }
     | if_expr
     ;

term = factor { ("*" | "/") factor } ;

factor = ID [ (":=" | "=") expr | "(" [ expr { "," expr } ] ")" ]
       | NUM
       | STR
       ;

if_expr = "if" expr "{" stmts "}" [ else_branch ] ;
else_branch = "else" (if_expr | "{" stmts "}") ;
